sudo: false
dist: trusty
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious"
  - "cpanm --installdeps --notest ."
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - "TEST_ONLINE=1"
before_script:
  - psql -c 'create database tree;' -U postgres


